### ISSUE TITLE
Talk about GitLab Pages

### ISSUE THREAD

**Issue by inem** [viennahtml/members#14]
Hey, I'd like to give a talk about GitLab Pages at the next meetup.
Here's my website: http://inem.at & twitter: @inemation
And few more info: http://inem.at/gitlab

**Comment by geraldb** [comment]
@inem  Wow. You're more than welcome. The next meetup is on Tue Apr 26th starting at 18.30.  Note the meetup is in Vienna, Austria and we're still a small group (maybe 20+ hard to say).  Also note we don't really have any budget for refunding travel expenses. However, you're - of course - invited to a free beer or two  (or coffee if you prefer ) ;-)    If you're still interested - you're signed up - just send me a title with a short summary (you can always change it later) and maybe a mini bio (just a line or two).   Cheers. Greeting from Vienna, Austria.

PS: Will try my best to promote the event and GitLab Pages. For example, let me know  if you're interested in a short Q&A for the next Static Times Newsletter #2  (per email I'd would send you 5 or 6 questions). PPS:  You can reach my per email too if your prefer ( gerald.bauer@gmail ).

**Comment by geraldb** [comment]
@inem FYI: I'm closing the Vienna.html talk ticket (thanks for getting back per email and the private email conversation). You're welcome to talk at Vienna.html anytime. Just open another ticket or send me an email. Enjoy the summer. Cheers.
