### ISSUE TITLE
Talk about Facebook Instant Articles for static sites

### ISSUE THREAD

**Issue by realityking** [viennahtml/members#16]
We recently set up our static blog for Instant Articles and I'd love to tell you about it.

I recently [blogged about it](https://www.contentful.com/blog/2016/05/13/facebook-instant-articles-and-contentful/) but the talk would be a bit less "let me tell you a story" and more a look into how our final solution looks like.

Summary for the website:

> Instant Articles is a feature of Facebook mobile apps to allows for the faster loading of content. However it does not just work with any website, articles need to be specially prepared. Rouven will show how Contentful implemented it for their blog, discuss alternative strategies and go trough some of the possibilities and limitations that Instand Articles bring.

**Comment by geraldb** [comment]
@realityking Fantastic. You're more than welcome. The next (and last meetup before the summer break) is on June 28th. And than restarting in Sept/Oct.  Note: The Vienna.html group is still small e.g. we expect about 10+ attendees (hard to say). Let me know if you're still interested. You can also reach me by email e.g. gerald.bauer AT gmail.com   Looking forward. Cheers.

**Comment by geraldb** [comment]
@realityking  If you don't mind I'm closing the ticket here. Thanks for getting back via email. Looking foward to your talk. Welcome. I've added your talk, summary, bio etc. to the event page. If anything is missing (needed/changed) etc. just let me know. Have a great weekend. Cheers. Greetings from Vienna.
