### ISSUE TITLE
Talks, Talks, Talks - Bring Your Mini Talks!

### ISSUE THREAD

**Issue by geraldb** [viennahtml/members#19]
Let us know. Post your topic here or ping us on twitter [viennahtml](https://twitter.com/viennahtml).  New speakers welcome. FYI: Next (5th meetup) on Wed Oct/19th starting at 18.30 @ sektor5 (Siebenbrunnengasse 44, Wien 5.)  See the [Vienna.html](http://viennahtml.github.io) site for more.

**Comment by apas** [comment]
Interested to present my static blog generator [athena](http://github.com/apas/athena).

**Comment by geraldb** [comment]
@apas  You're welcome. The next meetups are Wed Oct/19th + Nov/27th. Are you in Vienna, Austria (Wien, Österreich)?

**Comment by apas** [comment]
Yes.

**Comment by geraldb** [comment]
@apas Great. You're on. I've added the following title "Getting Started w/ Athena -A minimalist, light-weight static blog generator written in Python (based on Flask and Tufte CSS)" Note: Vienna.html is stll a tiny meetup e.g. maybe 5 or less attendee. If you send me or post a short bio (e.g. a paragraph about yourself  with links if desired) I will add it to the event site / posting. Looking forward. Welcome. Thanks.
