### ISSUE TITLE
Talks, Talks, Talks - Bring Your Mini Talks!

### ISSUE THREAD

**Issue by geraldb** [viennahtml/members#22]
Let us know. Post your topic here or ping us on twitter [viennahtml](https://twitter.com/viennahtml).  New speakers welcome. FYI: Next (6th meetup) on Tue Nov/22nd (last this year in 2016) starting at 18.30 @ sektor5 (Siebenbrunnengasse 44, Wien 5.)  See the [Vienna.html](http://viennahtml.github.io) site for more.

**Comment by metakermit** [comment]
Case study – building my web development portfolio website https://punkrockdev.com and some Google AdWords tweaks to get traffic.

Author – Dražen Lučanin (@metakermit), a full stack web developer, running a web development studio Punk Rock Dev.

**Comment by geraldb** [comment]
@metakermit Thanks for your talk and tips & tricks. Added your PunkRockDev.com case study to the site. Have a great week. Cheers.

**Comment by metakermit** [comment]
Cool, thanks Gerald :) You have a great week too!
